# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdevTest1',
                'doc_host': 'https://BruceDunn.github.io',
                'git_url': 'https://github.com/BruceDunn/nbdevTest1',
                'lib_path': 'nbdevTest1'},
  'syms': { 'nbdevTest1.cards': { 'nbdevTest1.cards.Card': ('cards.html#card', 'nbdevTest1/cards.py'),
                                  'nbdevTest1.cards.Card.__eq__': ('cards.html#card.__eq__', 'nbdevTest1/cards.py'),
                                  'nbdevTest1.cards.Card.__gt__': ('cards.html#card.__gt__', 'nbdevTest1/cards.py'),
                                  'nbdevTest1.cards.Card.__init__': ('cards.html#card.__init__', 'nbdevTest1/cards.py'),
                                  'nbdevTest1.cards.Card.__lt__': ('cards.html#card.__lt__', 'nbdevTest1/cards.py'),
                                  'nbdevTest1.cards.Card.__str__': ('cards.html#card.__str__', 'nbdevTest1/cards.py')},
            'nbdevTest1.deck': { 'nbdevTest1.deck.Deck': ('deck.html#deck', 'nbdevTest1/deck.py'),
                                 'nbdevTest1.deck.Deck.__init__': ('deck.html#deck.__init__', 'nbdevTest1/deck.py'),
                                 'nbdevTest1.deck.Deck.__str__': ('deck.html#deck.__str__', 'nbdevTest1/deck.py')}}}
